version: '2'
services:
  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pet_feeder

    ports:
      - 3308:3306